site_name: ESIHub Documentation
site_description: Documentation for the ESIHub Python client for EVE ONLINE ESI API
site_author: MelonCafe
repo_url: https://github.com/siege-green/esihub
repo_name: siege-green/esihub

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - User Guide:
    - Configuration: configuration.md
    - Usage:
        - General Usage: usage.md
        - Advanced Usage: advanced_usage.md
        - Performance Optimization: performance_optimization.md
    - Authentication: authentication.md
    - API Reference: api_reference.md
    - Error Handling: error_handling.md
    - Guide:
      - Detailed Guide: detailed_guide.md
      - Comprehensive Guide: comprehensive_guide.md
    - Examples: examples.md
    - Troubleshooting: troubleshooting.md
    - Development:
        - Development Setup: development_setup.md
        - Contributing: CONTRIBUTING.md
    - Python 3.11 Features: python_311_features.md


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/siege-green

copyright: Copyright &copy; 2024 Siege Green